### ISSUE TITLE
Time Log Problem

### ISSUE THREAD

**Issue by buddylindsey** [tulsawebdevs/ircbot#2]
The logs are recorded an hour ahead of time. There is no adjustment for daylight savings time, is my guess.

**Comment by zerokarmaleft** [comment]
In which time zone is your server located?

**Comment by buddylindsey** [comment]
It is on the east coast.

**Comment by zerokarmaleft** [comment]
Should be fixed with d974f9553b5ac6c21ab94692b8df30aefe31a1c3

**Comment by zerokarmaleft** [comment]
checked the timestamps of the irclogs, looks like this is fixed.
